In [2]:
import numpy as np

In [5]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [6]:
np.save('array1',arr1)

In [8]:
np.load('array1.npy') # call with .npy 

array([0, 1, 2, 3, 4])

In [9]:
arr = np.load('array1.npy')

In [10]:
arr2 = arr

In [11]:
arr

array([0, 1, 2, 3, 4])

In [12]:
arr2

array([0, 1, 2, 3, 4])

In [13]:
np.savez('ziparray.npz', x=arr1,y=arr2)

In [14]:
archive_array = np.load('ziparray.npz')

In [15]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [18]:
archive_array['y']

array([0, 1, 2, 3, 4])

In [19]:
arr = np.array([[1,2,3],[4,5,6]])

In [20]:
np.savetxt('mytextarray.txt',arr,delimiter=',') # save it as txt 

In [21]:
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [22]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])