In [1]:
import numpy as np 
import pandas as pd 
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2], index = ['T','U','V'])
ser2 = Series([3,4], index = ['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
# pd.concat 
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2], axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2],keys = ['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])


In [13]:
dframe1

X         Y         Z
0 -1.007767  0.605727 -0.542959
1  0.447477  0.186716  0.502076
2  0.470599 -1.195932  0.764701
3 -0.629474 -0.470270 -1.971361

In [14]:
dframe2

Y         Q         X
0  0.139533 -1.216591 -1.203529
1 -0.145701 -2.663657  0.275842
2 -0.360333 -0.247792  0.882980

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.007767  0.605727 -0.542959
1       NaN  0.447477  0.186716  0.502076
2       NaN  0.470599 -1.195932  0.764701
3       NaN -0.629474 -0.470270 -1.971361
0 -1.216591 -1.203529  0.139533       NaN
1 -2.663657  0.275842 -0.145701       NaN
2 -0.247792  0.882980 -0.360333       NaN

In [16]:
#ignore index if you like to 
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -1.007767  0.605727 -0.542959
1       NaN  0.447477  0.186716  0.502076
2       NaN  0.470599 -1.195932  0.764701
3       NaN -0.629474 -0.470270 -1.971361
4 -1.216591 -1.203529  0.139533       NaN
5 -2.663657  0.275842 -0.145701       NaN
6 -0.247792  0.882980 -0.360333       NaN